#!/bin/bash

apt-get update
apt-get install --yes libxml2-dev libxslt1-dev python-dev python-eventlet python-routes python-webob python-paramiko python-setuptools python-pip
cd /tmp/
git clone git://github.com/osrg/ryu.git
cd ryu
python ./setup.py install